[W socket.cpp:464] [c10d] The server socket cannot be initialized on [::]:0 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:697] [c10d] The client socket cannot be initialized to connect to [localhost]:44327 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:697] [c10d] The client socket cannot be initialized to connect to [localhost]:44327 (errno: 97 - Address family not supported by protocol).
[W socket.cpp:697] [c10d] The client socket cannot be initialized to connect to [localhost]:44327 (errno: 97 - Address family not supported by protocol).
Traceback (most recent call last):
  File "/jumbo/yaoqingyang/ouyangzhuoli/Robotics/VLA-Action-Head/vla-scripts/finetune_swanlab.py", line 26, in <module>
    from peft import LoraConfig, PeftModel, get_peft_model
  File "/jumbo/yaoqingyang/ouyangzhuoli/miniconda3/envs/openvla-oft/lib/python3.10/site-packages/peft/__init__.py", line 17, in <module>
    from .auto import (
  File "/jumbo/yaoqingyang/ouyangzhuoli/miniconda3/envs/openvla-oft/lib/python3.10/site-packages/peft/auto.py", line 32, in <module>
    from .peft_model import (
  File "/jumbo/yaoqingyang/ouyangzhuoli/miniconda3/envs/openvla-oft/lib/python3.10/site-packages/peft/peft_model.py", line 37, in <module>
    from transformers import Cache, DynamicCache, EncoderDecoderCache, PreTrainedModel
ImportError: cannot import name 'EncoderDecoderCache' from 'transformers' (/jumbo/yaoqingyang/ouyangzhuoli/miniconda3/envs/openvla-oft/lib/python3.10/site-packages/transformers/__init__.py)
[2025-08-08 05:52:51,093] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 1964559) of binary: /jumbo/yaoqingyang/ouyangzhuoli/miniconda3/envs/openvla-oft/bin/python3.10
Traceback (most recent call last):
  File "/jumbo/yaoqingyang/ouyangzhuoli/miniconda3/envs/openvla-oft/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/jumbo/yaoqingyang/ouyangzhuoli/miniconda3/envs/openvla-oft/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
  File "/jumbo/yaoqingyang/ouyangzhuoli/miniconda3/envs/openvla-oft/lib/python3.10/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/jumbo/yaoqingyang/ouyangzhuoli/miniconda3/envs/openvla-oft/lib/python3.10/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/jumbo/yaoqingyang/ouyangzhuoli/miniconda3/envs/openvla-oft/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/jumbo/yaoqingyang/ouyangzhuoli/miniconda3/envs/openvla-oft/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
vla-scripts/finetune_swanlab.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-08-08_05:52:51
  host      : eniac.cs.dartmouth.edu
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 1964559)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
